Rebuild kernel 5.17.5
Encountered strange failures with kprobe tests. All kernel symbols had
non-0 suffixes, like memblock_find_in_range.constprop.13. Rebuilding
the kernel fixed that for some reason.

--- FAIL: TestKprobeOffset (0.27s)
    --- FAIL: TestKprobeOffset/valid_offset#02 (0.11s)
        kprobe_amd64_test.go:69: unexpected err: 'creating perf_kprobe PMU: symbol '__x64_inet6_release+0x17' not found: file does not exist'
    --- FAIL: TestKprobeOffset/bad_insn_boundary#01 (0.01s)
        kprobe_amd64_test.go:63: expected err 'file does not exist', got '<nil>'
--- FAIL: TestKprobe (0.21s)
    --- FAIL: TestKprobe/async_resume.cold (0.04s)
        kprobe_test.go:36: creating perf_kprobe PMU: symbol '__x64_async_resume.cold+0x0' not found: file does not exist
    --- FAIL: TestKprobe/echo_char.isra.0 (0.04s)
        kprobe_test.go:36: creating perf_kprobe PMU: symbol '__x64_echo_char.isra.0+0x0' not found: file does not exist
    --- FAIL: TestKprobe/get_buffer.constprop.0 (0.04s)
        kprobe_test.go:36: creating perf_kprobe PMU: symbol '__x64_get_buffer.constprop.0+0x0' not found: file does not exist
    --- FAIL: TestKprobe/unregister_kprobes.part.0 (0.04s)
        kprobe_test.go:36: creating perf_kprobe PMU: symbol '__x64_unregister_kprobes.part.0+0x0' not found: file does not exist
--- FAIL: TestKretprobe (0.19s)
    --- FAIL: TestKretprobe/async_resume.cold (0.04s)
        kprobe_test.go:64: creating perf_kprobe PMU: symbol '__x64_async_resume.cold+0x0' not found: file does not exist
    --- FAIL: TestKretprobe/echo_char.isra.0 (0.04s)
        kprobe_test.go:64: creating perf_kprobe PMU: symbol '__x64_echo_char.isra.0+0x0' not found: file does not exist
    --- FAIL: TestKretprobe/get_buffer.constprop.0 (0.04s)
        kprobe_test.go:64: creating perf_kprobe PMU: symbol '__x64_get_buffer.constprop.0+0x0' not found: file does not exist
    --- FAIL: TestKretprobe/unregister_kprobes.part.0 (0.04s)
        kprobe_test.go:64: creating perf_kprobe PMU: symbol '__x64_unregister_kprobes.part.0+0x0' not found: file does not exist

Time to Dockerize the build process.

Signed-off-by: Timo Beckers <timo@isovalent.com>